name: Ubuntu

on: 
  workflow_dispatch:
    inputs:
      pincode:
        description: 'Six digit Pin'
        required: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: hostname -I
