name: Testing

on: 
  workflow_dispatch:
    inputs:
      authtoken:
        description: 'ngrok authtoken'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: http.server
      run: python -m http.server 8080 & 
    - name: localtunnel
      run: npm install -g localtunnel
    - name: tunnel password
      run: curl https://loca.lt/mytunnelpassword
    - name: test
      run: ls
    - name: test
      run: cd ../ | tree
    - name: webserver
      run: lt --port 8080
