name: Testing

on: 
  workflow_dispatch:
    inputs:
      authtoken:
        description: 'ngrok authtoken'
        required: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: pipe sub
      run: ssh pipe.pico.sh sub bug
