name: Testing

on: 
  workflow_dispatch:
    inputs:
      authtoken:
        description: 'ngrok authtoken'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing localtunnel
      run: npm install -g localtunnel
    - name: Fetching tunnel password
      run: curl https://loca.lt/mytunnelpassword
    - name: Installing running localtunnel
      run: lt --port 8080
