name: Testing

on: 
  workflow_dispatch:
    inputs:
      authtoken:
        description: 'ngrok authtoken'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: http.server
      run: python -m http.server 8080 & 
    - name: tor
      run: sudo apt install tor onionpipe
    - name: webserver
      run: sudo env "PATH=$PATH" /home/runner/work/ssh/ssh/onion 8080
